#!/bin/bash
WDIR="$1"
cd "$WDIR"
if [ "$2" ] ; then
	
	touch fixme.log
	find . -type f -print0 | while IFS= read -d '#FIXME' file
	do
  		# print every file
  		echo $file >> ./fixme.log
	done
fi
echo "finished"
